# This is a basic workflow to help you get started with Actions

name: Diff

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a diff
      - name: Download `ipsw`
        run: |
          brew install blacktop/tap/ipsw 

      # Runs a diff
      - name: Create report file
        run: |
          ipsw dl appledb --os macOS --version '${{ vars.PREV_MACOS_VERSION }}' --device iPhone16,2 --output /tmp/IPSW1 --confirm
          ipsw dl appledb --os macOS --version '${{ vars.NEXT_MACOS_VERSION }}' --device iPhone16,2 --output /tmp/IPSW2 --confirm
          ipsw diff --output . \
                    --markdown \
                    --fw \
                    --launchd \
                    --feat \
                    --strs \
                    /tmp/IPSW1/*.ipsw \
                    /tmp/IPSW2/*.ipsw
  
      - name: Commit report
        run: |
          git config --global user.name 'blacktop'
          git config --global user.email 'blacktop@users.noreply.github.com'
          git commit -am "Automated Diff"
          git push
